version: '3.8'

services:
  clutch-app:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - clutch-network

networks:
  clutch-network:
    driver: bridge